apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zammad-app
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://zammad.github.io/zammad-helm
      chart: zammad
      targetRevision: 13.0.13
      helm:
        valueFiles:
          - $values/ZammadValuesFolder/values.yaml

    - repoURL: https://github.com/LokiSahetia/Zammad-ArgoCD-Kubernetes.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: zammad

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

